### Import Libraries

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Health_Hospatility_security_project.csv")

### Read first Five rows

In [3]:
df.head()

,Hospital_ID,Hospital_Name,City,Hospital_Type,Beds,Daily_Patients,Avg_Wait_Time_Min,Contactless_Registration,Online_Appointment,Telemedicine,Digital_Health_Records,Cleanliness_Rating,Food_Service_Rating,Patient_Hospitality_Rating,CCTV_Coverage_Percentage,Security_Staff,Infection_Control_Score,Patient_Satisfaction,AI_Assisted_Services,Overall_Trend
0,H00001,Bengaluru Care Hospital 1,Pune,Government,958.0,90.0,120.0,yes,NO,No,No,NaN,4.6,3.6,NaN,101.0,82.0,2.4,NaN,NaN
1,H00002,Jaipur Care Hospital 2,NaN,Government,1118.0,1870.0,90.0,yes,YES,No,No,3.5,3.1,3.3,72.0,95.0,NaN,2.4,No,Digital Patient Care
2,H00003,Pune Care Hospital 3,NaN,Multispeciality,310.0,1365.0,115.0,yes,No,NaN,No,2.5,3.1,3.7,NaN,106.0,83.0,4.1,YES,NaN
3,H00004,Hyderabad Care Hospital 4,Coimbatore,Private,904.0,1570.0,30.0,Yes,YES,No,No,2.3,2.7,3.2,47.0,137.0,62.0,4.3,No,Digital Patient Care
4,H00005,Pune Care Hospital 5,Bengaluru,Specialty,578.0,571.0,149.0,Yes,No,Yes,Yes,4.3,NaN,3.8,71.0,72.0,86.0,4.5,yes,Digital Patient Care

### Last Five Rows

In [4]:
df.tail()

,Hospital_ID,Hospital_Name,City,Hospital_Type,Beds,Daily_Patients,Avg_Wait_Time_Min,Contactless_Registration,Online_Appointment,Telemedicine,Digital_Health_Records,Cleanliness_Rating,Food_Service_Rating,Patient_Hospitality_Rating,CCTV_Coverage_Percentage,Security_Staff,Infection_Control_Score,Patient_Satisfaction,AI_Assisted_Services,Overall_Trend
1595,H01596,Mumbai Care Hospital 1596,Madurai,Private,787.0,150.0,46.0,yes,Yes,Yes,No,2.8,2.9,4.1,52.0,172.0,NaN,2.6,YES,Digital Patient Care
1596,H01597,Chennai Care Hospital 1597,Coimbatore,Multispeciality,740.0,498.0,117.0,YES,Yes,Yes,Yes,3.7,3.3,3.9,NaN,105.0,78.0,4.4,YES,AI Healthcare
1597,H01598,Mumbai Care Hospital 1598,Pune,Specialty,NaN,1034.0,74.0,yes,NO,No,NaN,2.2,2.3,4.3,77.0,NaN,100.0,3.9,NaN,Digital Patient Care
1598,H01599,Jaipur Care Hospital 1599,Delhi,Multispeciality,414.0,256.0,77.0,yes,No,NaN,Yes,4.8,2.1,3.0,59.0,126.0,85.0,2.1,yes,Enhanced Security
1599,H01600,Chennai Care Hospital 1600,NaN,Government,798.0,1125.0,13.0,yes,Yes,No,No,4.7,3.8,4.1,84.0,75.0,50.0,NaN,NaN,Patient-Centric Care

### Particular Rows show

In [5]:
df.iloc[55:61]

,Hospital_ID,Hospital_Name,City,Hospital_Type,Beds,Daily_Patients,Avg_Wait_Time_Min,Contactless_Registration,Online_Appointment,Telemedicine,Digital_Health_Records,Cleanliness_Rating,Food_Service_Rating,Patient_Hospitality_Rating,CCTV_Coverage_Percentage,Security_Staff,Infection_Control_Score,Patient_Satisfaction,AI_Assisted_Services,Overall_Trend
55,H00056,Mumbai Care Hospital 56,Pune,Private,335.0,1583.0,14.0,YES,NO,Yes,No,4.8,NaN,2.9,34.0,108.0,84.0,4.2,YES,Digital Patient Care
56,H00057,Kochi Care Hospital 57,Mumbai,Specialty,602.0,394.0,66.0,YES,No,Yes,Yes,4.0,2.6,2.6,98.0,127.0,95.0,4.4,yes,NaN
57,H00058,Mumbai Care Hospital 58,Bengaluru,Private,NaN,257.0,69.0,NaN,NO,No,Yes,4.4,3.1,3.8,97.0,193.0,71.0,2.1,NaN,Contactless Healthcare
58,H00059,Delhi Care Hospital 59,Mumbai,Government,345.0,1568.0,NaN,Yes,Yes,NaN,No,4.4,2.4,3.7,43.0,23.0,88.0,3.6,yes,NaN
59,H00060,Hyderabad Care Hospital 60,Mumbai,Private,465.0,2191.0,NaN,yes,NO,NaN,Yes,4.9,5.0,2.7,33.0,175.0,63.0,3.4,Yes,Patient-Centric Care
60,H00061,Delhi Care Hospital 61,Jaipur,Government,646.0,1950.0,43.0,No,Yes,No,Yes,2.9,3.3,3.4,76.0,88.0,64.0,4.7,Yes,Contactless Healthcare

In [6]:
df.shape

(1600, 20)

### Columns Names

In [7]:
df.columns

Index(['Hospital_ID', 'Hospital_Name', 'City', 'Hospital_Type', 'Beds',
       'Daily_Patients', 'Avg_Wait_Time_Min', 'Contactless_Registration',
       'Online_Appointment', 'Telemedicine', 'Digital_Health_Records',
       'Cleanliness_Rating', 'Food_Service_Rating',
       'Patient_Hospitality_Rating', 'CCTV_Coverage_Percentage',
       'Security_Staff', 'Infection_Control_Score', 'Patient_Satisfaction',
       'AI_Assisted_Services', 'Overall_Trend'],
      dtype='object')

### Nulls

In [8]:
df.isnull().sum()

Hospital_ID                     0
Hospital_Name                   0
City                          172
Hospital_Type                 155
Beds                          163
Daily_Patients                175
Avg_Wait_Time_Min             165
Contactless_Registration      165
Online_Appointment            179
Telemedicine                  147
Digital_Health_Records        160
Cleanliness_Rating            141
Food_Service_Rating           159
Patient_Hospitality_Rating    175
CCTV_Coverage_Percentage      154
Security_Staff                159
Infection_Control_Score       165
Patient_Satisfaction          155
AI_Assisted_Services          163
Overall_Trend                 152
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hospital_ID                 1600 non-null   object
 1   Hospital_Name               1600 non-null   object
 2   City                        1428 non-null   object
 3   Hospital_Type               1445 non-null   object
 4   Beds                        1437 non-null   float64
 5   Daily_Patients              1425 non-null   float64
 6   Avg_Wait_Time_Min           1435 non-null   float64
 7   Contactless_Registration    1435 non-null   object
 8   Online_Appointment          1421 non-null   object
 9   Telemedicine                1453 non-null   object
 10  Digital_Health_Records      1440 non-null   object
 11  Cleanliness_Rating          1459 non-null   float64
 12  Food_Service_Rating         1441 non-null   float64
 13  Patient_Hospitality_Rating  1425 non-null   float64
 14  CCTV_Coverage_Percentage    1446 non-null   float64
 15  Security_Staff              1441 non-null   float64
 16  Infection_Control_Score     1435 non-null   float64
 17  Patient_Satisfaction        1445 non-null   float64
 18  AI_Assisted_Services        1437 non-null   object
 19  Overall_Trend               1448 non-null   object
dtypes: float64(10), object(10)
memory usage: 250.1+ KB

In [10]:
df.duplicated().sum()

0

In [11]:
# Fill with mean
df['Beds'] = df['Beds'].fillna(df['Beds'].mean())
 
# Fill with median
df['Daily_Patients'] = df['Daily_Patients'].fillna(df['Daily_Patients'].median())
 
# Fill with mode
df['City'] = df['City'].fillna(df['City'].mode()[0])
 
# Forward fill
df['Hospital_Type'] = df['Hospital_Type'].ffill()
 
# Backward fill
df['Telemedicine'] = df['Telemedicine'].bfill()
 
# Fill with a fixed value
df['Overall_Trend'] = df['Overall_Trend'].fillna("Unknown")
 
# Remaining numeric columns -> median
num_cols = ['Avg_Wait_Time_Min', 'Cleanliness_Rating', 'Food_Service_Rating',
            'Patient_Hospitality_Rating', 'CCTV_Coverage_Percentage',
            'Security_Staff', 'Infection_Control_Score', 'Patient_Satisfaction']
 
for col in num_cols:
    df[col] = df[col].fillna(df[col].median())
 
# Remaining text columns -> mode
text_cols = ['Contactless_Registration', 'Online_Appointment',
             'Digital_Health_Records', 'AI_Assisted_Services']
 
for col in text_cols:
    df[col] = df[col].fillna(df[col].mode()[0])
 
print(df.isna().sum())
 
df.to_csv("cleaned.csv", index=False)

Hospital_ID                   0
Hospital_Name                 0
City                          0
Hospital_Type                 0
Beds                          0
Daily_Patients                0
Avg_Wait_Time_Min             0
Contactless_Registration      0
Online_Appointment            0
Telemedicine                  0
Digital_Health_Records        0
Cleanliness_Rating            0
Food_Service_Rating           0
Patient_Hospitality_Rating    0
CCTV_Coverage_Percentage      0
Security_Staff                0
Infection_Control_Score       0
Patient_Satisfaction          0
AI_Assisted_Services          0
Overall_Trend                 0
dtype: int64

In [12]:
df.isnull().sum()

Hospital_ID                   0
Hospital_Name                 0
City                          0
Hospital_Type                 0
Beds                          0
Daily_Patients                0
Avg_Wait_Time_Min             0
Contactless_Registration      0
Online_Appointment            0
Telemedicine                  0
Digital_Health_Records        0
Cleanliness_Rating            0
Food_Service_Rating           0
Patient_Hospitality_Rating    0
CCTV_Coverage_Percentage      0
Security_Staff                0
Infection_Control_Score       0
Patient_Satisfaction          0
AI_Assisted_Services          0
Overall_Trend                 0
dtype: int64

## Data Preprocessing

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1600 entries, 0 to 1599
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hospital_ID                 1600 non-null   object
 1   Hospital_Name               1600 non-null   object
 2   City                        1600 non-null   object
 3   Hospital_Type               1600 non-null   object
 4   Beds                        1600 non-null   float64
 5   Daily_Patients              1600 non-null   float64
 6   Avg_Wait_Time_Min           1600 non-null   float64
 7   Contactless_Registration    1600 non-null   object
 8   Online_Appointment          1600 non-null   object
 9   Telemedicine                1600 non-null   object
 10  Digital_Health_Records      1600 non-null   object
 11  Cleanliness_Rating          1600 non-null   float64
 12  Food_Service_Rating         1600 non-null   float64
 13  Patient_Hospitality_Rating  1600 non-null   float64
 14  CCTV_Coverage_Percentage    1600 non-null   float64
 15  Security_Staff              1600 non-null   float64
 16  Infection_Control_Score     1600 non-null   float64
 17  Patient_Satisfaction        1600 non-null   float64
 18  AI_Assisted_Services        1600 non-null   object
 19  Overall_Trend               1600 non-null   object
dtypes: float64(10), object(10)
memory usage: 250.1+ KB

### Separate Float data types Columns names

In [14]:
print(df.select_dtypes(include=["float"]).columns)

Index(['Beds', 'Daily_Patients', 'Avg_Wait_Time_Min', 'Cleanliness_Rating',
       'Food_Service_Rating', 'Patient_Hospitality_Rating',
       'CCTV_Coverage_Percentage', 'Security_Staff', 'Infection_Control_Score',
       'Patient_Satisfaction'],
      dtype='object')

### Separate Object data types Columns names

In [15]:
print(df.select_dtypes(include=["object"]).columns)

Index(['Hospital_ID', 'Hospital_Name', 'City', 'Hospital_Type',
       'Contactless_Registration', 'Online_Appointment', 'Telemedicine',
       'Digital_Health_Records', 'AI_Assisted_Services', 'Overall_Trend'],
      dtype='object')

### Convert integer columns

In [16]:
int_col = [
"Beds",
"Daily_Patients",
"Security_Staff",

]

In [17]:
df[int_col] = df[int_col].astype(int)

### Convert float columns

In [18]:
float_col =[
    "Avg_Wait_Time_Min", "Cleanliness_Rating", "Food_Service_Rating",
    "Patient_Hospitality_Rating", "CCTV_Coverage_Percentage",
    "Infection_Control_Score", "Patient_Satisfaction"
]

In [20]:
df[float_col] =df[float_col].astype(float)

### Convert object columns

In [21]:
object_columns = [
    "Hospital_ID", "Hospital_Name", "City", "Hospital_Type",
    "Contactless_Registration", "Online_Appointment", "Telemedicine",
    "Digital_Health_Records", "AI_Assisted_Services", "Overall_Trend"
]

In [22]:
df[object_columns] = df[object_columns].astype(object)

### Handling Outliers

In [23]:
def beds_category(beds):
    if beds < 300:
        return "Small"
    elif beds < 800:
        return "Medium"
    elif beds < 1200:
        return "Large"
    else:
        return "Very Large"
df["Beds_1"] = df["Beds"].apply(beds_category)

In [24]:
def wait_time_category(minutes):
    if minutes < 30:
        return "Low"
    elif minutes < 75:
        return "Medium"
    elif minutes < 120:
        return "High"
    else:
        return "Very High"
df["Avg_Wait_Time_Min_1"] = df["Avg_Wait_Time_Min"].apply(wait_time_category)

In [25]:
def satisfaction_category(score):
    if score < 2.5:
        return "Poor"
    elif score < 3.5:
        return "Average"
    elif score < 4.5:
        return "Good"
    else:
        return "Excellent"
df["Patient_Satisfaction_1"] = df["Patient_Satisfaction"].apply(satisfaction_category)

In [26]:
def cctv_category(pct):
    if pct < 50:
        return "Low"
    elif pct < 75:
        return "Medium"
    else:
        return "High"
df["CCTV_Coverage_Percentage_1"] = df["CCTV_Coverage_Percentage"].apply(cctv_category)

### ENCODING CATEGORICAL VARIABLES

In [27]:
# One-Hot Encoding for multi-category columns
df = pd.get_dummies(
    df,
    columns=["City", "Hospital_Type", "Overall_Trend"],
    dtype=int
)

### Features Engineering

In [29]:
# Patients handled per bed - workload/capacity indicator
df["Patients_per_Bed"] = df["Daily_Patients"] / df["Beds"]

In [30]:
# Security staff available per 100 beds - security adequacy indicator
df["Security_per_100_Beds"] = (df["Security_Staff"] / df["Beds"]) * 100

### Features Selection

In [31]:
# Hospital_ID and Hospital_Name are identifiers, not useful for analysis/modeling
df = df.drop(["Hospital_ID", "Hospital_Name"], axis=1)

In [32]:
print(df.shape)
print(df.head())
df.to_csv("preprocessed_hospital_data.csv", index=False)

(1600, 44)
   Beds  Daily_Patients  Avg_Wait_Time_Min Contactless_Registration  \
0   958              90              120.0                      yes
1  1118            1870               90.0                      yes
2   310            1365              115.0                      yes
3   904            1570               30.0                      Yes
4   578             571              149.0                      Yes

  Online_Appointment Telemedicine Digital_Health_Records  Cleanliness_Rating  \
0                 NO           No                     No                 3.5
1                YES           No                     No                 3.5
2                 No           No                     No                 2.5
3                YES           No                     No                 2.3
4                 No          Yes                    Yes                 4.3

   Food_Service_Rating  Patient_Hospitality_Rating  ...  \
0                  4.6                         3.6  ...
1                  3.1                         3.3  ...
2                  3.1                         3.7  ...
3                  2.7                         3.2  ...
4                  3.5                         3.8  ...

   Overall_Trend_Contactless Healthcare  Overall_Trend_Digital Patient Care  \
0                                     0                                   0
1                                     0                                   1
2                                     0                                   0
3                                     0                                   1
4                                     0                                   1

   Overall_Trend_Enhanced Security  Overall_Trend_Green Hospital  \
0                                0                             0
1                                0                             0
2                                0                             0
3                                0                             0
4                                0                             0

  Overall_Trend_IoT Healthcare Overall_Trend_Patient-Centric Care  \
0                            0                                  0
1                            0                                  0
2                            0                                  0
3                            0                                  0
4                            0                                  0

  Overall_Trend_Smart Hospital Overall_Trend_Unknown Patients_per_Bed  \
0                            0                     1         0.093946
1                            0                     0         1.672630
2                            0                     1         4.403226
3                            0                     0         1.736726
4                            0                     0         0.987889

   Security_per_100_Beds
0              10.542797
1               8.497317
2              34.193548
3              15.154867
4              12.456747

[5 rows x 44 columns]